### ISSUE TITLE
v1.0 메인페이지

### ISSUE THREAD

**Issue by Banal972** [solo-service/mvz-frontend#1]
### Todo

- [x] 주간/주말 박스오피스 슬라이드
- [x] 일별 박스오피스 슬라이드
- [x] 슬라이드 기준으로 express 와 연동하여 포스터 get

### 작업 기간

2024.04.04 ~ 2024.04.07
